### ISSUE TITLE
Make `to` and `from` optional?

### ISSUE THREAD

**Issue by radix** [jondot/attrs-serde#1]
One thing that confused me when trying out this library is that I was trying to serialize some existing models I had. All I was getting back from `to_dict` was `{}`. I didn't realize that the `to` and `from` metadata were required. Would it be acceptable if they weren't, and instead defaulted to the equivalent of `[attr_name]`? So a model that contained a field `phone = attr.ib()` would be serialized as a dict with `{"phone": ...}`?

**Comment by jondot** [comment]
thanks! I believe this is now implemented by #3

**Comment by jondot** [comment]
hey, love your work BTW, just went over a few of your projects 😉
